# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = "Mohammad Rahchamani's resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Mohammad Rahchamani"
        tagline = "Software Engineer"
        avatar = "avatar.webp"







    [params.contact]
        enable = true
        location = "Tehran, Iran"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0098 901 4943114"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "mohammad.rahchamani@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.rahchamani.me"







    [params.skills]
        enable = true
        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        title = "Swift/Objective-C"
        [[params.skills.list.items]]
        title = "Java/Kotlin"
        [[params.skills.list.items]]
        title = "JavaScript/Node.js/Express.js/koa.js/Adonis.js/Sequelize.js"
        [[params.skills.list.items]]
        title = "Python/Django/Flask/SqlAlchemy"
        [[params.skills.list.items]]
        title = "Docker/AWS"
        [[params.skills.list.items]]
        title = "TensorFlow/Keras/Pandas/Numpy/Scikit-learn"
        [[params.skills.list.items]]
        title = "PostgreSQL/MySQL/SQLite/MongoDB/Redis/GraphQL"
        [[params.skills.list.items]]
        title = "HTML/CSS/Bootstrap/Foundation/Tailwind"
        [[params.skills.list.items]]
        title = "Software Architecture/Design Patterns"
        [[params.skills.list.items]]
        title = "Linux/Shell/Git"
        [[params.skills.list.items]]
        title = "Mobile application development"
        [[params.skills.list.items]]
        title = "API design and implementation"
        [[params.skills.list.items]]
        title = "Design and implement database structures"
        [[params.skills.list.items]]
        title = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        title = "Effective communication"
        [[params.skills.list.items]]
        title = "Teamwork"
        [[params.skills.list.items]]
        title = "Leadership"
        [[params.skills.list.items]]
        title = "Problem solving"
        [[params.skills.list.items]]
        title = "Numeracy"
        [[params.skills.list.items]]
        title = "Creative thinking"
        [[params.skills.list.items]]
        title = "Time management"
        [[params.skills.list.items]]
        title = "Self motivated"
        [[params.skills.list.items]]
        title = "Business awareness"
        








    [params.education]
        enable = false

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University College London"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Maths and Physics"
        university = "Imperial College London"
        dates = "2007 - 2010"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Highly motivated, self-managed software developer with experience in a wide variety of different technologies. Team player with leadership skills, able to make technical decisions, communicate and take responsibility for the team. Built products from scratch and worked on big projects. A constant learner with a growth mindset who is willing to learn from others, tackle difficulties, and solve problems. Able to change the viewpoint from big-picture to focusing on details based on the product requirements and development stage."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Full Stack Engineer"
        dates = "Sep 2019 - Present"
        company = "BetterSleep"
        details = "We built sleep tracker and smart alarm applications for iOS and WatchOS. As a full-stack developer, I had to communicate with the product manager to understand and meet marketing needs and deadlines. I also had to communicate with our designer to fine-tune the details of our app to create a seamless user experience. Collaborating closely with the product, marketing, and the design team helped me to get better at communication. I had the opportunity to work with the latest technologies in the Apple ecosystem."
        [[params.experience.list.items]]
        details = "Developed multiple MVPs to help the product team with the decisions"
        [[params.experience.list.items]]
        details = "Took responsibility for the product from scratch"
        [[params.experience.list.items]]
        details = "Developed iOS and WatchOS apps with SwiftUI"
        [[params.experience.list.items]]
        details = "Developed a backend to serve users, process payments and sync data"

        [[params.experience.list]]
        title = "Freelance Software Developer"
        dates = "Apr 2017 - Oct 2019"
        company = "-"
        details = "I worked on a wide range of projects to expand my knowledge and expertise in new areas. Working with people from different domains helped me to better understand different customer needs and change my perspective more easily."
        [[params.experience.list.items]]
        details = "Developed AI based Forex trading bot with MQL, RabbitMQ and Python"
        [[params.experience.list.items]]
        details = "Experienced building prototypes with embedded computers"
        [[params.experience.list.items]]
        details = "Developed multiple chat bots with JavaScript and Python"
        [[params.experience.list.items]]
        details = "Developed mobile applications with ReactNative"

        [[params.experience.list]]
        title = "iOS Developer"
        dates = "Mar 2016 - Nov 2016"
        company = "Pichak"
        details = "I worked on applications with millions of daily active users(Betternet and Hexatech). We were on top of the charts in the App Store with a 4.5+ rating. I got to know about analytic tools and user experience design as well as some of product design methods. I had the opportunity to work with great engineers and I learned a lot from them."
        [[params.experience.list.items]]
        details = "Experienced serving a large user base"
        [[params.experience.list.items]]
        details = "Implemented our custom VPN protocol on the client"
        [[params.experience.list.items]]
        details = "Improved app stability by writing tests and setting up a Jenkins server for CI/CD"
        [[params.experience.list.items]]
        details = "Experienced working on legacy code of large projects"

        [[params.experience.list]]
        title = "Full Stack Engineer"
        dates = "May 2015 - Feb 2016"
        company = "Holimo"
        details = "I worked on a trivia game on android. It was a multi player, online game in which users had to guess the distorted image, with some hints."
        [[params.experience.list.items]]
        details = "Created a native android trivia game"
        [[params.experience.list.items]]
        details = "Enhanced client server communication using socket programming"
        [[params.experience.list.items]]
        details = "Implemented custom Image manipulation algorithms on client"
        [[params.experience.list.items]]
        details = "Co-ordinated with the design team to deliver a better user experience"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "Dec 2013 - May 2015"
        company = "ATD"
        details = "We were building mobile applications for our customers and the thech stack for each project was depending on the requirements of the customer. I worked on native android and iOS applications as well as hybird apps using phonegap. I also worked on our backend team where we developed our APIs using node.js."
        [[params.experience.list.items]]
        details = "Developed multiple native and hybrid apps"
        [[params.experience.list.items]]
        details = "Led our internal tools development team"
        [[params.experience.list.items]]
        details = "Trained new team members"
        [[params.experience.list.items]]
        details = "Organized multi-platform projects"
        [[params.experience.list.items]]
        details = "Negotiated with customers to better understand their needs"
        










    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "KN2C"
        meta = "Khajeh Nasireddin Toosi University"
        tagline = "I was the lead software developer in our SSL(Small Size League) robotic team. We developed our agents' decision making system and Co-ordinated with our hardware team. "








    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true


        [[params.social.list]]
        icon = "fab fa-stack-overflow"
        url = "//stackoverflow.com/users/2810741/mohammad-rahchamani"
        title = "StackOverflow account"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/mohammad-rahchamani"
        title = "LinkedIn account"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/mohammad-rahchamani"
        title = "Github account"





