# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Mohammad Rahchamani"
        tagline = "Software Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Tehran, Iran"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0098 901 4943114"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "mohammad.rahchamani@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.rahchamani.me"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = false

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University College London"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Maths and Physics"
        university = "Imperial College London"
        dates = "2007 - 2010"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Highly motivated, self-managed software developer with experience in a wide variety of different technologies. Team player with leadership skills, able to make technical decisions, communicate and take responsibility for the team. Built products from scratch and worked on big projects. A constant learner who is willing to learn from others, tackle difficulties and solve problems. Able to change the viewpoint from big-picture to focusing on details based on the product requirements and development stage."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Full Stack Engineer"
        dates = "Sep 2019 - Present"
        company = "BetterSleep"
        details = "We built sleep tracker and smart alarm applications (BetterSleep and Good Sleep) for iOS and WatchOS. As a full-stack developer, I had to communicate with the product manager to understand and meet marketing needs and deadlines. I also have to communicate with our designer to fine-tune the details of our app to create a seamless user experience. Collaborating closely with the product, marketing, and the design team helped me to get better at communication. I had the opportunity to work with the latest technologies in the Apple ecosystem."
        [[params.experience.list.items]]
        details = "Developed multiple MVPs to help the product team with the decisions"
        [[params.experience.list.items]]
        details = "Took responsibility for the product from scratch"
        [[params.experience.list.items]]
        details = "Developed iOS and WatchOS apps with SwiftUI"
        [[params.experience.list.items]]
        details = "Developed Python backend to serve users and sync data"
        [[params.experience.list.items]]
        details = "Used PostgresQL as our database"
        [[params.experience.list.items]]
        details = "Used AWS to deploy our backend and database"
        [[params.experience.list.items]]
        details = "Used iOS 13+ and WatchOS 6+ features"

        [[params.experience.list]]
        title = "Freelance Software Developer"
        dates = "Apr 2017 - Oct 2019"
        company = "-"
        details = "I worked on a wide range of projects to expand my knowledge and expertise in new areas. Working with people from different domains helped me to better understand different customer needs and change my perspective more easily."
        [[params.experience.list.items]]
        details = "Developed AI based Forex trading bot with MQL, RabbitMQ and Python"
        [[params.experience.list.items]]
        details = "Developed multiple bots with JavaScript and Python"
        [[params.experience.list.items]]
        details = "Developed mobile application with ReactNative"

        [[params.experience.list]]
        title = "iOS Developer"
        dates = "Mar 2016 - Nov 2016"
        company = "Pichak"
        details = "I worked on applications with millions of daily active users(Betternet and Hexatech). We were on top of the charts in App Store with 4.5+ rating. I got to know about analytic tools and user experience design as well as some of product design methods. I had the opportunity to work with great engineers and I learned a lot from them."
        [[params.experience.list.items]]
        details = "Experienced serving large user base"
        [[params.experience.list.items]]
        details = "Implemented our custom VPN protocol on our iOS app"
        [[params.experience.list.items]]
        details = "Set up Jenkins Server for CI/CD"
        [[params.experience.list.items]]
        details = "Experienced working on legacy code on large projects"

        [[params.experience.list]]
        title = "Full Stack Engineer"
        dates = "May 2015 - Feb 2016"
        company = "Holimo"
        details = "I worked on a trivia game on android. It was a multi player, online game in which users had to guess the distorted image, with some hints."
        [[params.experience.list.items]]
        details = "Worked on a native android trivia game"
        [[params.experience.list.items]]
        details = "Used socket programming for server communication"
        [[params.experience.list.items]]
        details = "Implemented custom Image manipulation algorithms on client"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "Dec 2013 - May 2015"
        company = "ATD"
        details = "We were building mobile applications for our customers and the thech stack for each project was depending on the requirements of the customer. I worked on native android and iOS applications as well as hybird apps using phonegap. I also worked on our backend team where we developed our APIs using node.js."
        [[params.experience.list.items]]
        details = "Lead our internal tools development team"
        [[params.experience.list.items]]
        details = "Developed customizable platform to generate API code"
        [[params.experience.list.items]]
        details = "Developed multiple native and hybrid apps"










    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"





